### ISSUE TITLE
Failed to resolve: local.component:app-core:1.1.2

### ISSUE THREAD

**Issue by frankjiayounuli** [codyer/EasyAmmeter#1]
这个依赖提示没有

**Comment by codyer** [comment]
> 这个依赖提示没有

app 的gradle里面依赖改成github地址那个，本地仓库你没有配置是找不到的。

**Comment by frankjiayounuli** [comment]
> > 这个依赖提示没有
> 
> app 的gradle里面依赖改成github地址那个，本地仓库你没有配置是找不到的。

改成了github那个也一样错误。github那个换低版本没问题，但是里面有些类缺失。请您看下

**Comment by codyer** [comment]
> > > 这个依赖提示没有
> > 
> > 
> > app 的gradle里面依赖改成github地址那个，本地仓库你没有配置是找不到的。
> 
> 改成了github那个也一样错误。github那个换低版本没问题，但是里面有些类缺失。请您看下

升级到1.1.3，我这边试了是可以的，你试试新的版本是否可以

**Comment by frankjiayounuli** [comment]
> > > > 这个依赖提示没有
> > > 
> > > 
> > > app 的gradle里面依赖改成github地址那个，本地仓库你没有配置是找不到的。
> > 
> > 
> > 改成了github那个也一样错误。github那个换低版本没问题，但是里面有些类缺失。请您看下
> 
> 升级到1.1.3，我这边试了是可以的，你试试新的版本是否可以

好的，我download最新版本试试看
